Drain the log iterator in order to cancel the log operation
Otherwise it would intermittently crash because the log operation is
acutally run in another thread, which may not have completed:

Traceback (most recent call last):
  . . .
  File "svn-fex", line 208, in main
    ra.reparent(url)
_ra.BusyException: Remote access object already in use